Updated tools and installation doc.

diff --git a/bin/make_flux b/bin/make_flux
--- a/bin/make_flux
+++ b/bin/make_flux
@@ -84,10 +84,30 @@ aws secretsmanager describe-secret --secret-id $cluster/flux/ca.pem 2>/dev/null
 if [ $? -ne 0 ]
 then
     aws secretsmanager create-secret --name $cluster/flux/ca.pem --secret-string "$(cat $DIR/ca.pem)"
+    if [ $? -ne 0 ]
+    then
+	    echo "${red}[x] failed to create ca.pem to AWS${reset}"
+	    exit 1
+    fi
     aws secretsmanager create-secret --name $cluster/flux/ca-key.pem --secret-string "$(cat $DIR/ca-key.pem)"
+    if [ $? -ne 0 ]
+    then
+	    echo "${red}[x] failed to create ca-key.pem to AWS${reset}"
+	    exit 1
+    fi
 else
     aws secretsmanager update-secret --secret-id $cluster/flux/ca.pem --secret-string "$(cat $DIR/ca.pem)"
+    if [ $? -ne 0 ]
+    then
+	    echo "${red}[x] failed to update ca.pem to AWS${reset}"
+	    exit 1
+    fi
     aws secretsmanager update-secret --secret-id $cluster/flux/ca-key.pem --secret-string "$(cat $DIR/ca-key.pem)"
+    if [ $? -ne 0 ]
+    then
+	    echo "${red}[x] failed to update ca-key.pem to AWS${reset}"
+	    exit 1
+    fi
 fi
 
 make_cert $cluster
diff --git a/bin/make_random_secrets b/bin/make_random_secrets
--- a/bin/make_random_secrets
+++ b/bin/make_random_secrets
@@ -1,4 +1,4 @@
-#!/bin/bash -xv
+#!/bin/bash
 #
 # Install random secrets into cluster
 #
@@ -14,7 +14,7 @@ REMOTE_REPO=${1:-$REMOTE_REPO}
 
 if [ -z "$REMOTE_REPO" ]
 then
-        echo "${red}must provide REMOTE_REPO${reset}"
+        echo "${red}[x] must provide REMOTE_REPO${reset}"
         exit 1
 fi
 
@@ -27,8 +27,8 @@ fi
 
 if [ -z "$GITHUB_TOKEN" ]
 then
-        echo "${red}\$GITHUB_TOKEN required.${reset}"
-        exit
+        echo "${red}[x] \$GITHUB_TOKEN required.${reset}"
+        exit 1
 fi
 
 remotebase=$(basename $remote)
@@ -56,16 +56,17 @@ CONFIG_DIR=$(realpath .)
 # extract values to use for templating
 export ClusterName=$(yq r values.yaml cluster.metadata.name)
 
-echo "${magenta}creating config for cluster $ClusterName in repo $remote${reset}"
+echo "${magenta}[i] creating random secrets for cluster $ClusterName in repo $remote${reset}"
 
 # run template processor to create non-Tidepool services
 cd $QUICKSTART_DIR
-for dir in base namespaces
+for dir in pkgs 
 do
   for file in $(find $dir -type f -print)
   do
         if [ "${file: -12}" == "-secret.yaml" ]
 	then
+                echo "${magenta}[i] creating secret $(basename $file)${reset}"
 		kubectl apply -f $file 
 	fi
   done
@@ -77,9 +78,12 @@ for env in $environments
 do
         for file in $(find $CHART_DIR -name \*secret.yaml -print)
         do
+		echo "${magenta}[i] creating secret $env/$(basename $file)${reset}"
 		helm template --namespace $env --set global.secret.enabled=true $CHART_DIR -f  $CHART_DIR/values.yaml -x $file  | kubectl apply -f -
 	done
 done
+
+echo "${magenta}[i] done${reset}"
 
 # clean up
 rm -rf $mytmpdir
